INFO 2020-04-16 15:40:02,305 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 17:14:11,030 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 17:14:43,556 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 17:15:25,512 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 18:06:54,643 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-16 18:07:10,716 log 228 Not Found: /
WARNING 2020-04-16 18:07:10,717 basehttp 154 "GET / HTTP/1.1" 404 2129
WARNING 2020-04-16 18:07:10,803 log 228 Not Found: /favicon.ico
WARNING 2020-04-16 18:07:10,804 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2180
INFO 2020-04-16 18:54:43,369 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:24:19,987 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:24:57,690 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:28:16,412 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:29:00,031 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-16 19:29:00,873 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:56:55,069 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:57:45,896 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:01:34,272 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:09:29,115 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:16:43,111 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:21:36,258 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:24:27,597 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:27:42,578 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-04-16 20:27:43,000 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:34:03,842 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-04-16 20:34:04,315 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:43:35,529 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:43:49,142 basehttp 154 "GET /usernames/sfdgrgh/count/ HTTP/1.1" 200 39
WARNING 2020-04-16 20:43:59,659 log 228 Not Found: /carts/simple/
WARNING 2020-04-16 20:43:59,666 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2183
WARNING 2020-04-16 20:44:01,577 log 228 Not Found: /image_codes/8a5c35d5-08d6-4743-9e6d-57d83b8f4859/
WARNING 2020-04-16 20:44:01,579 basehttp 154 "GET /image_codes/8a5c35d5-08d6-4743-9e6d-57d83b8f4859/ HTTP/1.1" 404 2291
INFO 2020-04-16 20:44:12,038 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:13,689 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:21,167 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:23,257 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:28,865 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:33,042 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:40,958 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:48,774 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-16 20:44:56,545 log 228 Not Found: /image_codes/b9805de3-cb23-4f0a-b1c2-cdaabec64311/
WARNING 2020-04-16 20:44:56,547 basehttp 154 "GET /image_codes/b9805de3-cb23-4f0a-b1c2-cdaabec64311/ HTTP/1.1" 404 2291
WARNING 2020-04-16 20:44:58,447 log 228 Not Found: /image_codes/c7f45a9b-dca5-4eed-bb42-eb0dec4c0316/
WARNING 2020-04-16 20:44:58,449 basehttp 154 "GET /image_codes/c7f45a9b-dca5-4eed-bb42-eb0dec4c0316/ HTTP/1.1" 404 2291
WARNING 2020-04-16 20:45:00,425 log 228 Not Found: /image_codes/bd44dbf5-5ae9-4360-98ec-7ebcb44fe4a4/
WARNING 2020-04-16 20:45:00,429 basehttp 154 "GET /image_codes/bd44dbf5-5ae9-4360-98ec-7ebcb44fe4a4/ HTTP/1.1" 404 2291
INFO 2020-04-16 20:45:04,210 basehttp 154 "GET /usernames/regerryt/count/ HTTP/1.1" 200 39
WARNING 2020-04-16 20:45:31,215 log 228 Not Found: /image_codes/ec90d94b-15aa-47aa-9043-e84c976ccad7/
WARNING 2020-04-16 20:45:31,217 basehttp 154 "GET /image_codes/ec90d94b-15aa-47aa-9043-e84c976ccad7/ HTTP/1.1" 404 2291
WARNING 2020-04-16 20:45:33,187 log 228 Not Found: /image_codes/c9f8b034-6f0a-463b-97ec-e3dbdf196987/
WARNING 2020-04-16 20:45:33,191 basehttp 154 "GET /image_codes/c9f8b034-6f0a-463b-97ec-e3dbdf196987/ HTTP/1.1" 404 2291
INFO 2020-04-16 20:45:39,193 basehttp 154 "GET /usernames/sdgwet/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:46:41,061 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:47:35,032 basehttp 154 "GET /usernames/jolfiej/count/ HTTP/1.1" 200 39
WARNING 2020-04-16 20:47:35,085 log 228 Not Found: /favicon.ico
WARNING 2020-04-16 20:47:35,087 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2171
INFO 2020-04-16 20:56:33,531 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 21:02:06,516 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 21:02:09,054 basehttp 154 "GET /mobiles/14111111111/count/ HTTP/1.1" 200 39
INFO 2020-04-20 16:23:06,989 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 16:24:24,588 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 16:24:40,903 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 16:32:49,670 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 17:57:52,490 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 17:58:10,006 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 17:58:10,427 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 17:58:21,484 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 17:58:32,560 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 17:58:35,691 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:00:25,361 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:00:36,024 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:01:08,693 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 18:01:10,898 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:05:07,217 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 18:05:07,597 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:05:10,572 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:08:17,921 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:10:43,431 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:11:05,252 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 18:11:07,158 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:11:47,488 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2020-04-20 18:11:49,448 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:11:57,469 basehttp 154 "GET /usernames/sadgfdg/count/ HTTP/1.1" 200 39
INFO 2020-04-20 18:12:11,760 basehttp 154 "GET /mobiles/13111111111/count/ HTTP/1.1" 200 39
WARNING 2020-04-20 18:12:40,637 log 228 Not Found: /image_codes/c978fd7b-8183-4bc8-841e-33dfd4abc50e/
WARNING 2020-04-20 18:12:40,638 basehttp 154 "GET /image_codes/c978fd7b-8183-4bc8-841e-33dfd4abc50e/ HTTP/1.1" 404 2667
WARNING 2020-04-20 18:12:41,323 log 228 Not Found: /image_codes/f23c9a80-63e6-4f95-b47b-c7f6ac695fbd/
WARNING 2020-04-20 18:12:41,328 basehttp 154 "GET /image_codes/f23c9a80-63e6-4f95-b47b-c7f6ac695fbd/ HTTP/1.1" 404 2667
WARNING 2020-04-20 18:12:42,239 log 228 Not Found: /image_codes/9db2c29d-b66d-42d6-8919-b976844f09d1/
WARNING 2020-04-20 18:12:42,242 basehttp 154 "GET /image_codes/9db2c29d-b66d-42d6-8919-b976844f09d1/ HTTP/1.1" 404 2667
INFO 2020-04-20 18:23:03,055 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2020-04-20 18:23:03,468 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-20 18:23:08,713 log 228 Internal Server Error: /image_codes/3bf9d355-e4a3-4fe5-8c10-a83fb71b3092/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 12, in get
    text, image = captcha.generate_captche()
AttributeError: 'Captcha' object has no attribute 'generate_captche'
ERROR 2020-04-20 18:23:08,714 basehttp 154 "GET /image_codes/3bf9d355-e4a3-4fe5-8c10-a83fb71b3092/ HTTP/1.1" 500 83882
ERROR 2020-04-20 18:23:17,843 log 228 Internal Server Error: /image_codes/cf5f76a2-ad3c-4494-9309-6173f33817ef/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 12, in get
    text, image = captcha.generate_captche()
AttributeError: 'Captcha' object has no attribute 'generate_captche'
ERROR 2020-04-20 18:23:17,845 basehttp 154 "GET /image_codes/cf5f76a2-ad3c-4494-9309-6173f33817ef/ HTTP/1.1" 500 83882
ERROR 2020-04-20 18:23:19,120 log 228 Internal Server Error: /image_codes/ae11266d-63b7-466e-a622-add43dfa9e70/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 12, in get
    text, image = captcha.generate_captche()
AttributeError: 'Captcha' object has no attribute 'generate_captche'
ERROR 2020-04-20 18:23:19,121 basehttp 154 "GET /image_codes/ae11266d-63b7-466e-a622-add43dfa9e70/ HTTP/1.1" 500 83882
INFO 2020-04-20 18:46:46,357 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-20 18:46:51,356 log 228 Internal Server Error: /image_codes/8398141b-7acf-4167-935f-c233a250815e/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 12, in get
    text, image = captcha.generate_captche()
AttributeError: 'Captcha' object has no attribute 'generate_captche'
ERROR 2020-04-20 18:46:51,358 basehttp 154 "GET /image_codes/8398141b-7acf-4167-935f-c233a250815e/ HTTP/1.1" 500 83882
INFO 2020-04-20 18:52:19,714 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:52:22,830 basehttp 154 "GET /image_codes/e9bd0bd3-636d-4e67-b9a2-f19fef406bf6/ HTTP/1.1" 200 2869
INFO 2020-04-20 20:27:04,793 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:27:10,411 basehttp 154 "GET /image_codes/d1c1e70b-701a-4459-b904-1cdbd0aebfaf/ HTTP/1.1" 200 3212
INFO 2020-04-20 20:27:11,790 basehttp 154 "GET /image_codes/016b5c25-7e59-4faa-a3f0-1455e68d06b1/ HTTP/1.1" 200 3072
INFO 2020-04-20 20:27:12,479 basehttp 154 "GET /image_codes/094c6dde-c0b7-431f-8b38-b5fd1a7dcc04/ HTTP/1.1" 200 3218
INFO 2020-04-20 20:27:13,088 basehttp 154 "GET /image_codes/7d9bb812-f640-4bf4-a45f-f15d29033bd4/ HTTP/1.1" 200 3310
INFO 2020-04-20 20:27:13,762 basehttp 154 "GET /image_codes/745773f7-674e-469e-a4f4-60b3a8be3bac/ HTTP/1.1" 200 2933
INFO 2020-04-20 20:31:32,275 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 20:31:32,687 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:31:41,521 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 20:31:41,922 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:31:50,729 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 20:31:51,109 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:32:20,587 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 20:32:20,999 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:32:33,051 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 20:32:33,508 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:40:48,932 basehttp 154 "GET /image_codes/63d3c5fb-e355-4cb9-b1d7-fc5d74153ca2/ HTTP/1.1" 200 3345
INFO 2020-04-20 20:41:09,777 basehttp 154 "GET /image_codes/6ce2946b-e54e-4b3d-af96-c4f63a30b610/ HTTP/1.1" 200 2941
INFO 2020-04-20 20:41:11,127 basehttp 154 "GET /image_codes/3bd45479-6b89-4bb1-90f6-260d45abae19/ HTTP/1.1" 200 3141
INFO 2020-04-20 20:41:13,165 basehttp 154 "GET /image_codes/24d3058b-b683-49c3-a8a7-0028ac97c5b3/ HTTP/1.1" 200 3565
INFO 2020-04-20 20:41:14,262 basehttp 154 "GET /image_codes/189e3c8e-a77b-4f93-a277-ef1a49f48024/ HTTP/1.1" 200 3033
INFO 2020-04-21 11:37:56,900 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 11:38:36,387 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-21 11:38:39,198 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 11:38:51,344 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2020-04-21 11:38:51,764 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 11:38:54,228 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 11:39:02,428 basehttp 154 "GET /image_codes/1f107da4-0dcf-46e1-a63d-5522769e9c5f/ HTTP/1.1" 200 2967
INFO 2020-04-21 11:39:17,448 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:39:36,007 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:39:46,638 basehttp 154 "GET /sms_codes/13652421005/?image_code=q60i&image_code_id=1f107da4-0dcf-46e1-a63d-5522769e9c5f HTTP/1.1" 200 63
INFO 2020-04-21 11:39:46,647 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:43:57,021 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 11:44:01,924 basehttp 154 "GET /image_codes/eb35ad4c-095d-4508-a742-29c0b172d22c/ HTTP/1.1" 200 3300
INFO 2020-04-21 11:44:07,617 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:08,149 basehttp 154 "GET /sms_codes/13652421005/?image_code=wzvf&image_code_id=eb35ad4c-095d-4508-a742-29c0b172d22c HTTP/1.1" 200 61
INFO 2020-04-21 11:44:41,333 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:41,339 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:41,349 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
WARNING 2020-04-21 11:44:41,363 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:41,364 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
WARNING 2020-04-21 11:44:42,482 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:42,487 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:44:42,491 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:42,491 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:43,124 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:43,126 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:44:43,130 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:43,132 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:43,556 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:43,560 log 228 Not Found: /register/
INFO 2020-04-21 11:44:43,561 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:43,561 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
WARNING 2020-04-21 11:44:43,835 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:43,841 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:44:43,847 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:43,848 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:43,990 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:43,996 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:44:43,997 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:43,998 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:44,160 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:44,165 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:44,169 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:44,178 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
WARNING 2020-04-21 11:44:44,327 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:44,328 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:44:44,334 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:44,334 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:44,498 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:44,498 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:44,503 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:44,506 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:45:46,907 basehttp 154 "GET /sms_codes/13652421005/?image_code=wzvf&image_code_id=eb35ad4c-095d-4508-a742-29c0b172d22c HTTP/1.1" 200 69
INFO 2020-04-21 11:45:46,911 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:01:18,112 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 12:01:23,633 basehttp 154 "GET /image_codes/c6b4c67c-bf08-4454-8c25-b9929ce5c40c/ HTTP/1.1" 200 3387
INFO 2020-04-21 12:01:28,156 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:01:37,767 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:01:43,367 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:01:43,922 basehttp 154 "GET /sms_codes/13652421005/?image_code=opz8&image_code_id=c6b4c67c-bf08-4454-8c25-b9929ce5c40c HTTP/1.1" 200 61
INFO 2020-04-21 12:02:02,525 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:02:02,528 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:02:04,786 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:02:04,788 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:02:04,791 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
WARNING 2020-04-21 12:02:04,805 log 228 Not Found: /register/
WARNING 2020-04-21 12:02:04,806 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
WARNING 2020-04-21 12:02:05,913 log 228 Not Found: /register/
INFO 2020-04-21 12:02:05,917 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:02:05,917 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 12:02:05,919 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 13:05:17,570 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-21 13:05:47,956 log 228 Not Found: /carts/simple/
WARNING 2020-04-21 13:05:47,957 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2749
INFO 2020-04-21 13:05:50,308 basehttp 154 "GET /image_codes/fcc9c72e-4d77-4a47-9c23-7359fdf3d48d/ HTTP/1.1" 200 3517
INFO 2020-04-21 13:05:54,874 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:06:05,398 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:06:11,518 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:06:11,674 basehttp 154 "GET /sms_codes/13652421005/?image_code=tgmd&image_code_id=fcc9c72e-4d77-4a47-9c23-7359fdf3d48d HTTP/1.1" 200 61
INFO 2020-04-21 13:07:13,106 basehttp 154 "GET /image_codes/e6b48d5f-7881-4cd2-a428-fd5edb59713c/ HTTP/1.1" 200 3455
INFO 2020-04-21 13:07:26,460 basehttp 154 "GET /sms_codes/13652421005/?image_code=ebyj&image_code_id=e6b48d5f-7881-4cd2-a428-fd5edb59713c HTTP/1.1" 200 61
INFO 2020-04-21 13:07:26,462 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:08:31,718 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:08:31,723 basehttp 154 "GET /sms_codes/13652421005/?image_code=ebyj&image_code_id=e6b48d5f-7881-4cd2-a428-fd5edb59713c HTTP/1.1" 200 69
INFO 2020-04-21 13:11:25,161 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:13:09,577 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:13:24,970 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/celery_tasks/sms/tasks.py changed, reloading.
INFO 2020-04-21 13:13:25,403 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:13:27,287 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:13:51,540 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:17:21,250 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:20:10,815 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:21:42,212 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/celery_tasks/sms/yuntongxun/ccp_sms.py changed, reloading.
INFO 2020-04-21 13:21:42,651 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-21 13:21:53,570 log 228 Not Found: /carts/simple/
WARNING 2020-04-21 13:21:53,572 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2749
INFO 2020-04-21 13:21:55,773 basehttp 154 "GET /image_codes/a7772438-29f6-4138-9c99-c2026779ed1b/ HTTP/1.1" 200 3001
INFO 2020-04-21 13:21:58,364 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:22:06,449 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:22:11,787 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:22:11,921 basehttp 154 "GET /sms_codes/13652421005/?image_code=ihsk&image_code_id=a7772438-29f6-4138-9c99-c2026779ed1b HTTP/1.1" 200 61
INFO 2020-04-21 13:42:14,018 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:42:42,935 basehttp 154 "GET /admin/ HTTP/1.1" 302 0
INFO 2020-04-21 13:42:42,999 basehttp 154 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1819
INFO 2020-04-21 13:42:43,153 basehttp 154 "GET /static/admin/css/base.css HTTP/1.1" 200 16378
INFO 2020-04-21 13:42:43,160 basehttp 154 "GET /static/admin/css/login.css HTTP/1.1" 200 1233
INFO 2020-04-21 13:42:43,164 basehttp 154 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
INFO 2020-04-21 13:42:43,188 basehttp 154 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
WARNING 2020-04-21 13:42:43,390 log 228 Not Found: /favicon.ico
WARNING 2020-04-21 13:42:43,392 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2737
INFO 2020-04-21 13:42:43,394 basehttp 154 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
INFO 2020-04-21 13:42:43,398 basehttp 154 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
INFO 2020-04-21 13:42:52,791 basehttp 154 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1980
INFO 2020-04-21 13:42:52,894 basehttp 154 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
INFO 2020-04-21 13:48:27,610 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:48:35,465 basehttp 154 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2020-04-21 13:48:35,517 basehttp 154 "GET /admin/ HTTP/1.1" 200 3289
INFO 2020-04-21 13:48:35,603 basehttp 154 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
INFO 2020-04-21 13:48:35,611 basehttp 154 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2020-04-21 13:48:35,627 basehttp 154 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2020-04-21 13:48:43,431 basehttp 154 "GET /admin/users/user/add/ HTTP/1.1" 200 13275
INFO 2020-04-21 13:48:43,464 basehttp 154 "GET /static/admin/css/forms.css HTTP/1.1" 200 8518
INFO 2020-04-21 13:48:43,501 basehttp 154 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
INFO 2020-04-21 13:48:43,525 basehttp 154 "GET /admin/jsi18n/ HTTP/1.1" 200 3223
INFO 2020-04-21 13:48:43,527 basehttp 154 "GET /static/admin/js/calendar.js HTTP/1.1" 200 7777
INFO 2020-04-21 13:48:43,528 basehttp 154 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
INFO 2020-04-21 13:48:43,531 basehttp 154 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20218
INFO 2020-04-21 13:48:43,532 basehttp 154 "GET /static/admin/js/core.js HTTP/1.1" 200 7099
INFO 2020-04-21 13:48:43,542 basehttp 154 "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
INFO 2020-04-21 13:48:43,546 basehttp 154 "GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
INFO 2020-04-21 13:48:43,547 basehttp 154 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 271817
INFO 2020-04-21 13:48:43,553 basehttp 154 "GET /static/admin/js/actions.js HTTP/1.1" 200 6766
INFO 2020-04-21 13:48:43,559 basehttp 154 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
INFO 2020-04-21 13:48:43,582 basehttp 154 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
INFO 2020-04-21 13:48:43,597 basehttp 154 "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
INFO 2020-04-21 13:48:43,598 basehttp 154 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
INFO 2020-04-21 13:48:43,778 basehttp 154 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2020-04-21 13:48:43,787 basehttp 154 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2020-04-21 13:49:01,301 basehttp 154 "GET /admin/ HTTP/1.1" 200 3289
INFO 2020-04-22 03:03:32,292 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:09:05,905 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:18:41,890 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:22:27,303 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:24:31,364 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:25:06,235 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:33:35,068 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:35:58,729 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:36:05,608 basehttp 154 "GET /image_codes/cb75999c-9b71-4fc3-b82e-7d9bd977c2e8/ HTTP/1.1" 200 3192
INFO 2020-04-22 03:36:13,705 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:36:13,878 basehttp 154 "GET /sms_codes/13652421005/?image_code=xhko&image_code_id=cb75999c-9b71-4fc3-b82e-7d9bd977c2e8 HTTP/1.1" 200 61
INFO 2020-04-22 03:36:49,045 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2020-04-22 03:36:49,111 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:36:49,123 basehttp 154 "GET /usernames/meihao/count/ HTTP/1.1" 200 39
ERROR 2020-04-22 03:36:49,131 log 228 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 42, in post
    if not all(username, password, password2, mobile, allow, sms_code_client):
TypeError: all() takes exactly one argument (6 given)
ERROR 2020-04-22 03:36:49,135 basehttp 154 "POST /register/ HTTP/1.1" 500 84267
INFO 2020-04-22 03:36:52,657 basehttp 154 "GET /usernames/meihao/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:36:52,661 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
ERROR 2020-04-22 03:36:52,694 log 228 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 42, in post
    if not all(username, password, password2, mobile, allow, sms_code_client):
TypeError: all() takes exactly one argument (6 given)
ERROR 2020-04-22 03:36:52,695 basehttp 154 "POST /register/ HTTP/1.1" 500 84267
INFO 2020-04-22 03:41:13,775 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:41:18,171 basehttp 154 "GET /image_codes/aaf196cf-931a-4bc1-8cad-1d28a6335803/ HTTP/1.1" 200 3456
INFO 2020-04-22 03:41:29,854 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:41:30,005 basehttp 154 "GET /sms_codes/13652421005/?image_code=cqer&image_code_id=aaf196cf-931a-4bc1-8cad-1d28a6335803 HTTP/1.1" 200 61
INFO 2020-04-22 03:41:52,840 basehttp 154 "GET /usernames/meihao/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:41:52,840 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:41:53,082 basehttp 154 "POST /register/ HTTP/1.1" 200 27
WARNING 2020-04-22 03:41:53,626 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 03:41:53,631 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2907
INFO 2020-04-22 04:06:29,486 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 04:07:11,349 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
ERROR 2020-04-22 04:07:11,441 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 82, in post
    dict = json.load(request.body.decode())
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
ERROR 2020-04-22 04:07:11,443 basehttp 154 "POST /login/ HTTP/1.1" 500 87877
INFO 2020-04-22 04:07:35,970 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 04:07:47,453 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 04:08:07,838 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-22 04:08:17,446 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 82, in post
    dict = json.load(request.body.decode())
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
ERROR 2020-04-22 04:08:17,449 basehttp 154 "POST /login/ HTTP/1.1" 500 87877
ERROR 2020-04-22 04:08:18,356 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 82, in post
    dict = json.load(request.body.decode())
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
ERROR 2020-04-22 04:08:18,357 basehttp 154 "POST /login/ HTTP/1.1" 500 87877
INFO 2020-04-22 04:11:14,727 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 04:11:23,707 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 04:11:23,709 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 04:11:42,598 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
ERROR 2020-04-22 04:11:42,672 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 82, in post
    dict = json.load(request.body.decode())
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
ERROR 2020-04-22 04:11:42,673 basehttp 154 "POST /login/ HTTP/1.1" 500 87877
INFO 2020-04-22 04:12:33,822 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-22 04:12:36,943 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 82, in post
    dict = json.load(request.body.decode())
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
ERROR 2020-04-22 04:12:36,944 basehttp 154 "POST /login/ HTTP/1.1" 500 87877
INFO 2020-04-22 04:15:52,316 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 04:15:55,628 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 04:15:56,083 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 04:15:56,084 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 04:27:37,166 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 04:28:23,787 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 04:28:23,789 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 04:28:33,092 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 04:28:33,239 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 04:28:33,644 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 04:28:33,645 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
WARNING 2020-04-22 04:28:44,277 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 04:28:44,278 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 05:42:31,436 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 05:42:37,749 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 05:42:37,750 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 05:42:52,883 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
ERROR 2020-04-22 05:42:52,939 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/utils/module_loading.py", line 20, in import_string
    return getattr(module, class_name)
AttributeError: module 'users.utils' has no attribute 'UsernameMobileAuthBackend'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 91, in post
    user = authenticate(username=username, password=password)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/utils/module_loading.py", line 24, in import_string
    ) from err
ImportError: Module "users.utils" does not define a "UsernameMobileAuthBackend" attribute/class
ERROR 2020-04-22 05:42:52,941 basehttp 154 "POST /login/ HTTP/1.1" 500 104959
INFO 2020-04-22 05:43:59,896 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 05:44:03,220 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 05:44:03,674 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 05:44:03,677 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 05:45:33,775 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 05:46:41,553 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 05:46:46,141 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 05:46:46,266 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 05:46:46,778 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 05:46:46,779 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 05:47:34,530 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 05:47:40,756 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 05:47:40,760 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 05:47:43,835 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 05:48:44,978 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:16:54,031 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-22 06:16:55,408 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:18:01,966 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:18:36,497 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:20:22,401 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:22:29,363 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:22:36,152 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 06:22:36,310 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 06:22:36,770 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 06:22:36,770 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 07:16:48,919 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 07:16:55,415 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 07:16:55,416 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
INFO 2020-04-22 07:16:59,949 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 07:16:59,983 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 07:17:19,332 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 07:17:22,320 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 07:17:22,457 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 07:17:22,890 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 07:17:22,892 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
INFO 2020-04-22 07:17:31,993 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 07:18:12,215 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 07:18:12,898 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 07:18:12,905 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
INFO 2020-04-22 07:18:35,538 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 09:12:28,085 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 09:12:40,662 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 09:12:40,664 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3372
INFO 2020-04-22 09:12:44,107 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 09:12:44,254 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 09:12:44,657 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 09:12:44,658 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3372
INFO 2020-04-22 09:12:48,242 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 14:12:44,408 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 14:12:50,395 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 14:12:50,419 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 14:12:53,692 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
INFO 2020-04-22 19:04:06,164 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 19:04:57,091 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/oauth/utils.py changed, reloading.
INFO 2020-04-22 19:04:57,526 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 19:05:00,717 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 19:05:25,961 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:05:25,962 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:05:38,974 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
INFO 2020-04-22 19:06:18,737 basehttp 154 "GET /oauth_callback/?code=F0A13719D65885585D82415D4518F262 HTTP/1.1" 200 263
INFO 2020-04-22 19:06:18,815 basehttp 154 "GET /image_codes/fa40a9ec-98b0-4c4d-8fb8-31bf8813542a/ HTTP/1.1" 200 3485
INFO 2020-04-22 19:06:45,406 basehttp 154 "GET /sms_codes/13652421005/?image_code=mwvo&image_code_id=fa40a9ec-98b0-4c4d-8fb8-31bf8813542a HTTP/1.1" 200 61
INFO 2020-04-22 19:07:06,785 basehttp 154 "OPTIONS /oauth_callback/ HTTP/1.1" 200 0
INFO 2020-04-22 19:07:06,962 basehttp 154 "POST /oauth_callback/ HTTP/1.1" 200 27
WARNING 2020-04-22 19:07:07,569 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:07:07,570 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:07:26,666 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 19:07:26,671 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 19:07:26,734 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 19:07:26,737 basehttp 154 "GET /info/ HTTP/1.1" 500 74282
INFO 2020-04-22 19:07:40,569 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 19:07:40,592 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 19:07:44,405 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
INFO 2020-04-22 19:07:59,881 basehttp 154 "GET /oauth_callback/?code=F6F582B7A47FF2854CEB670A60A9FAAE HTTP/1.1" 200 27
WARNING 2020-04-22 19:08:00,359 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:08:00,360 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:10:58,344 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:10:58,346 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:11:36,792 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:11:36,793 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:11:38,261 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 19:11:38,294 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
WARNING 2020-04-22 19:11:47,714 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:11:47,715 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:12:00,996 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:12:00,997 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:12:55,158 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:12:55,163 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:13:02,361 log 228 Not Found: /carts/
WARNING 2020-04-22 19:13:02,362 basehttp 154 "GET /carts/ HTTP/1.1" 404 3681
INFO 2020-04-22 19:13:05,575 basehttp 154 "OPTIONS /carts/selection/ HTTP/1.1" 200 0
WARNING 2020-04-22 19:13:05,585 log 228 Not Found: /carts/selection/
WARNING 2020-04-22 19:13:05,587 basehttp 154 "PUT /carts/selection/ HTTP/1.1" 404 3711
WARNING 2020-04-22 19:13:49,594 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:13:49,595 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:16:01,179 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 19:16:12,256 log 228 Not Found: /
WARNING 2020-04-22 19:16:12,258 basehttp 154 "GET / HTTP/1.1" 404 3639
WARNING 2020-04-22 19:16:12,366 log 228 Not Found: /favicon.ico
WARNING 2020-04-22 19:16:12,370 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 3690
WARNING 2020-04-22 19:16:22,281 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:16:22,289 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:16:30,723 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:16:30,725 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:17:20,419 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:17:20,420 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:18:07,904 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:18:07,905 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:55:10,502 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 19:55:17,648 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:55:17,648 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:55:30,969 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 19:55:31,102 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 19:55:31,516 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:55:31,517 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:59:36,470 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-04-22 19:59:45,758 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 19:59:46,204 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:59:46,206 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:01:09,339 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:01:09,340 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:01:18,248 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:01:18,252 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:01:18,299 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:01:18,301 basehttp 154 "GET /info/ HTTP/1.1" 500 74282
INFO 2020-04-22 20:01:21,335 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 20:01:21,461 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:01:21,912 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:01:21,912 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:01:23,931 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:01:23,942 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:01:24,008 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:01:24,012 basehttp 154 "GET /info/ HTTP/1.1" 500 74282
INFO 2020-04-22 20:01:31,515 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:01:31,946 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:01:31,947 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:02:12,407 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:02:12,408 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:02:12,469 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:02:12,470 basehttp 154 "GET /info/ HTTP/1.1" 500 74282
WARNING 2020-04-22 20:09:58,750 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:09:58,762 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:09:58,894 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:09:58,897 basehttp 154 "GET /info/ HTTP/1.1" 500 74312
INFO 2020-04-22 20:13:16,410 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 20:13:21,816 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 20:13:21,952 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:13:22,390 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:13:22,391 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3714
WARNING 2020-04-22 20:13:23,982 log 228 Not Found: /info/
WARNING 2020-04-22 20:13:23,985 basehttp 154 "GET /info/ HTTP/1.1" 404 3690
WARNING 2020-04-22 20:13:23,994 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:13:23,995 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3726
INFO 2020-04-22 20:15:16,049 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:15:16,770 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:15:16,774 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3714
INFO 2020-04-22 20:16:18,763 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-04-22 20:16:19,567 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 20:18:29,388 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 20:18:29,429 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 20:18:32,804 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:18:33,334 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:18:33,336 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:18:49,575 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:18:49,581 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:18:49,626 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:18:49,628 basehttp 154 "GET /info/ HTTP/1.1" 500 74312
WARNING 2020-04-22 20:19:45,550 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:19:45,554 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:19:45,608 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:19:45,610 basehttp 154 "GET /info/ HTTP/1.1" 500 74282
INFO 2020-04-22 20:22:06,516 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 20:22:10,033 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:22:10,036 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
INFO 2020-04-22 20:22:10,055 basehttp 154 "GET /info/ HTTP/1.1" 200 125
INFO 2020-04-22 20:23:05,397 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 20:23:09,494 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:23:09,955 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:23:09,957 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:23:11,890 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:23:11,892 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
INFO 2020-04-22 20:23:11,909 basehttp 154 "GET /info/ HTTP/1.1" 200 125
